FROM node:20

WORKDIR /app

COPY package*.json ./

RUN apt-get update && apt-get install -y netcat-openbsd
RUN npm install

COPY scripts/wait-for-mongo.sh ./scripts/wait-for-mongo.sh
RUN chmod +x ./scripts/wait-for-mongo.sh

EXPOSE 3000

CMD [ "./scripts/wait-for-mongo.sh", "mongo-user", "npm", "start" ]
