/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUserDialog: typeof import('./src/components/dialogs/CreateUserDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AuthForm: typeof import('./src/components/common/AuthForm.vue')['default']
    AuthLayout: typeof import('./src/components/layout/AuthLayout.vue')['default']
    BlockUserDialog: typeof import('./src/components/dialogs/BlockUserDialog.vue')['default']
    CollapseToggle: typeof import('./src/components/layout/CollapseToggle.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    CopyIcon: typeof import('./src/components/common/CopyIcon.vue')['default']
    CreateUserDialog: typeof import('./src/components/dialogs/CreateUserDialog.vue')['default']
    DeleteUserDialog: typeof import('./src/components/dialogs/DeleteUserDialog.vue')['default']
    EditUserDialog: typeof import('./src/components/dialogs/EditUserDialog.vue')['default']
    ExpandedRowContent: typeof import('./src/components/table/ExpandedRowContent.vue')['default']
    ExportFooter: typeof import('./src/components/table/UserTableExportFooter.vue')['default']
    ExportUsersDialog: typeof import('./src/components/dialogs/ExportUsersDialog.vue')['default']
    FilterUsersDialog: typeof import('./src/components/dialogs/FilterUsersDialog.vue')['default']
    ImportUsersDialog: typeof import('./src/components/dialogs/ImportUsersDialog.vue')['default']
    NavigationItems: typeof import('./src/components/layout/NavigationItems.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchUsersDialog: typeof import('./src/components/dialogs/SearchUsersDialog.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    SigninForm: typeof import('./src/components/common/SigninForm.vue')['default']
    ThemeToggle: typeof import('./src/components/layout/ThemeToggle.vue')['default']
    TODO: typeof import('./src/components/TODO.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    UserForm: typeof import('./src/components/common/UserForm.vue')['default']
    UserMenu: typeof import('./src/components/layout/UserMenu.vue')['default']
    UserTable: typeof import('./src/components/table/UserTable.vue')['default']
    UserTableExportFooter: typeof import('./src/components/table/UserTableExportFooter.vue')['default']
    UserTableRowActions: typeof import('./src/components/table/UserTableRowActions.vue')['default']
    UserTableToolbar: typeof import('./src/components/table/UserTableToolbar.vue')['default']
  }
}
